### PR TITLE
Fixed compilation of tier1 caused by min/max.

### LINKED ISSUE #93: Tier1 is Failing to Compile on Ubuntu 20.04.3 LTS
It looks like it is failing due to not finding the definition of min and max.  Some examples:

```
hl2sdk/tier1/KeyValues.cpp:109:21: error: ‘max’ was not declared in this scope; did you mean ‘Max’?

hl2sdk/tier1/diff.cpp:222:27: error: ‘min’ was not declared in this scope; did you mean ‘Min’
```

### PR DESCRIPTION
**Pull request by taiyungwang**
Fixes #93

### CODE REVIEW

**Review by peace-maker — APPROVED** [review]

**Comment by taiyungwang** [comment]
Thanks for the approval.  I don't have write access to this repo, so someone else would with access will need to merge the changes for me.
