### ISSUE TITLE
Tier1 is Failing to Compile on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by taiyungwang** [alliedmodders/hl2sdk#93]
It looks like it is failing due to not finding the definition of min and max.  Some examples:

```
hl2sdk/tier1/KeyValues.cpp:109:21: error: ‘max’ was not declared in this scope; did you mean ‘Max’?

hl2sdk/tier1/diff.cpp:222:27: error: ‘min’ was not declared in this scope; did you mean ‘Min’
```

**Comment by peace-maker** [comment]
Which branch?

**Comment by taiyungwang** [comment]
Sorry, sdk2013.

**Comment by peace-maker** [comment]
Ah, true, some uses of `min` and `max` slipped through on https://github.com/alliedmodders/hl2sdk/commit/c33f7155e9aff9573c20d86e10c8158425a3d67a 
tier1 isn't compiled regularly, so this didn't show up.

If you don't mind, you could create a PR to replace the calls with ones to `V_min` and `V_max` respectively?
